site:
  title: Test
  url: https://matbgn.gitlab.io/antora/
  start_page: subtest::index.adoc
content:
  # edit_url: '{web_url}/blob/{refname}/{path}'
  sources:
  - url: ./
    branches: master
    start_path: antora-docs
ui:
  bundle:
    url: "node_modules/@djencks/lunr-ui/build/lunr-ui-bundle.zip"
    snapshot: true
extensions:
  - path: "@djencks/antora-lunr"
output:
  dir: ./docs